AIBH/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aibh.urls'))
]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aibh/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'aibh'



urlpatterns = [
    path('', views.index, name='index'),
    path('admin_panelle/', views.admin_panelle, name='admin_panelle'),
    path('admin_panelle/', views.admin_panelle, name='admin_panelle'),
    path('blog/delete/<int:blog_id>/', views.delete_blog, name='delete_blog'),
    path('product/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('blog/edit/<int:blog_id>/', views.edit_blog, name='edit_blog'),
    path('product/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('boutique/', views.boutique, name='boutique'),
    path('bienetre/', views.bienetre, name='bienetre'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('user_profile_view/', views.user_profile_view, name='user_profile_view'),
    path('blog/<int:pk>/', views.blog_detail, name='blog_detail'),
    path('contact/', views.contact, name='contact'),
    path('add-category/', views.add_category, name='add_category'),
    path('panier/', views.afficher_panier, name='afficher_panier'),
    path('logout/', views.custom_logout, name='logout'),
    path('vider-panier/', views.vider_panier, name='vider_panier'),
    path('toggle-affiliation/', views.toggle_affiliation, name='toggle_affiliation'),
    path('ajouter_au_panier/<int:product_id>/', views.ajouter_au_panier, name='ajouter_au_panier'),
    path('panier/', views.afficher_panier, name='panier_view'),
    path('enregistrer-achat/', views.enregistrer_achat, name='enregistrer_achat'),
    path('soumettre-avis/', views.soumettre_avis, name='soumettre_avis'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('generate-affiliate-link/<int:product_id>/', views.generate_affiliate_link, name='generate_affiliate_link'),
    path('produits-etrangers/', views.foreign_products_view, name='foreign_products'),
    path('produits-locaux/', views.local_products_view, name='local_products'),


 
]

aibh/forms.py
# forms.py

from django import forms
from django.contrib.auth.models import User

class CheckoutForm(forms.Form):
    pays = forms.CharField(max_length=100, required=True)
    ville = forms.CharField(max_length=100, required=True)
    numero_de_telephone = forms.CharField(max_length=15, required=True)
    adresse = forms.CharField(max_length=255, required=True)
    code_postale = forms.CharField(max_length=20, required=False)

class CreateAccountForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    numero_de_telephone = forms.CharField(label='Numéro de téléphone', max_length=15, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'numero_de_telephone']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les mots de passe ne correspondent pas.")
        return password2

aibh/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from .models import Product, Country,AffiliateLink
from decimal import Decimal
import random
from .models import Profile,Panier,Achat,AvisClient
import stripe
import paypalrestsdk
import requests
from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from decimal import Decimal
import random
import string
from django.shortcuts import render, redirect
from django.conf import settings
import paypalrestsdk




import stripe
import paypalrestsdk
import requests
from django.conf import settings
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from decimal import Decimal
import random
import string
from django.conf import settings
import stripe
import paypalrestsdk
import requests
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from decimal import Decimal

def index(request):
    # Récupération des objets Blog et Product avec tri inverse
    blogs = Blog.objects.all().order_by('-created_at')  # Tri des blogs du plus récent au plus ancien
    products = Product.objects.all().order_by('-created_at')  # Tri des produits du plus récent au plus ancien
    avis_autorises = AvisClient.objects.filter(autorise=True)
    
    # Récupération des catégories
    categories = list(Category.objects.values('id', 'name'))  # Convertir en liste de dictionnaires

    # Préparation du contexte pour le template
    context = {
        'blogs': blogs,
        'products': products,
        'categories': categories,  # Liste des catégories
        'avis_autorises': avis_autorises,  # Ajout des avis autorisés au contexte
    }
    
    return render(request, 'index.html', context)

from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def boutique(request):
    # Récupération des objets Blog et Product avec tri inverse
    blogs = Blog.objects.all().order_by('-created_at')  # Tri des blogs du plus récent au plus ancien
    products = Product.objects.all().order_by('-created_at')  # Tri des produits du plus récent au plus ancien

    # Récupération des catégories
    categories = list(Category.objects.values('id', 'name'))  # Convertir en liste de dictionnaires

    # Initialiser le compteur de produits dans le panier à zéro
    panier_count = 0

    if request.user.is_authenticated:
        # Récupération du profil de l'utilisateur connecté
        profile = get_object_or_404(Profile, user=request.user)
        
        # Compter le nombre de produits dans le panier de l'utilisateur
        panier_count = Panier.objects.filter(profile=profile).count()

    # Préparation du contexte pour le template
    context = {
        'blogs': blogs,
        'products': products,
        'categories': categories,  # Liste des catégories
        'panier_count': panier_count,  # Nombre de produits dans le panier
    }
    
    return render(request, 'boutique.html', context)



# views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def blog_detail(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    return render(request, 'blog_detail.html', {'blog': blog})





from django.shortcuts import render, redirect
from .models import Product, Blog, Category
# views.py
from django.shortcuts import render, redirect
from .models import Blog, Product, Category,AvisClient

def admin_panelle(request):
    if request.method == 'POST':
        # Gestion de l'ajout de produit
        if 'add_product' in request.POST:
            name = request.POST.get('name')
            category_id = request.POST.get('category')
            description = request.POST.get('description')
            price_commercial = request.POST.get('price_commercial')
            price_partner = request.POST.get('price_partner')
            image = request.FILES.get('image')
            product_type = request.POST.get('product_type')
            marge = request.POST.get('marge')
            prix_livraison = request.POST.get('prix_livraison')
            country_id = request.POST.get('country') if product_type == 'foreign' else None

            category = Category.objects.get(id=category_id)
            country = Country.objects.get(id=country_id) if country_id else None

            Product.objects.create(
                name=name,
                category=category,
                description=description,
                price_commercial=price_commercial,
                price_partner=price_partner,
                image=image,
                product_type=product_type,
                country=country,
                marge=marge,
                prix_livraison=prix_livraison
            )
            return redirect('aibh:admin_panelle')

        # Gestion de l'ajout de blog
        elif 'add_blog' in request.POST:
            title = request.POST.get('title')
            category_id = request.POST.get('category')
            description = request.POST.get('description')
            image = request.FILES.get('image')

            category = Category.objects.get(id=category_id)

            Blog.objects.create(
                title=title,
                category=category,
                description=description,
                image=image
            )
            return redirect('aibh:admin_panelle')
        
         # Gestion de l'autorisation des avis
        elif 'update_avis' in request.POST:
            for key, value in request.POST.items():
                if key.startswith('avis_'):
                    avis_id = key.split('_')[1]
                    autorise = value == 'on'
                    try:
                        avis = AvisClient.objects.get(id=avis_id)
                        avis.autorise = autorise
                        avis.save()
                    except AvisClient.DoesNotExist:
                        pass

        # Gérer les autres cas...

    # Préparation du contexte pour le template
    countries = Country.objects.all()
    blogs = Blog.objects.all().order_by('-created_at')
    products = Product.objects.all().order_by('-created_at')
    categories = Category.objects.all()
    avis_clients = AvisClient.objects.all()
    achats = Achat.objects.all().order_by('-created_at')  # Ajout de la récupération des achats
    product_type_choices = Product.PRODUCT_TYPE_CHOICES

    context = {
        'blogs': blogs,
        'products': products,
        'categories': categories,
        'countries': countries,
        'achats': achats,
        'product_type_choices': product_type_choices,
        'avis_clients': avis_clients,  # Ajout des avis au contexte
    }
    
    return render(request, 'admin.html', context)



# views.py
from django.shortcuts import get_object_or_404, redirect
from .models import Blog, Product

def delete_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    blog.delete()
    return redirect('aibh:admin_panelle')

def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    product.delete()
    return redirect('aibh:admin_panelle')



from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog, Product, Category

def edit_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    
    if request.method == 'POST':
        blog.title = request.POST.get('title')
        blog.category = Category.objects.get(id=request.POST.get('category'))
        blog.description = request.POST.get('description')
        if 'image' in request.FILES:
            blog.image = request.FILES.get('image')
        blog.save()
        return redirect('aibh:admin_panelle')

    categories = Category.objects.all()
    context = {
        'blog': blog,
        'categories': categories
    }
    return render(request, 'admin.html', context)



def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    
    if request.method == 'POST':
        product.name = request.POST.get('name')
        product.category = Category.objects.get(id=request.POST.get('category'))
        product.description = request.POST.get('description')
        product.price_commercial = request.POST.get('price_commercial')
        product.price_partner = request.POST.get('price_partner')
        if 'image' in request.FILES:
            product.image = request.FILES.get('image')
        product.save()
        return redirect('aibh:admin_panelle')

    categories = Category.objects.all()
    context = {
        'product': product,
        'categories': categories
    }
    return render(request, 'admin.html', context)


from django.shortcuts import render
from .models import Blog, Product, Category

def bienetre(request):
    # Récupération des catégories
    categories = Category.objects.all()
    avis_autorises = AvisClient.objects.filter(autorise=True)

    # Vérification si une catégorie a été sélectionnée
    category_id = request.GET.get('category_id')
    if category_id:
        selected_category = Category.objects.get(id=category_id)
        blogs = Blog.objects.filter(category=selected_category).order_by('-created_at')
        products = Product.objects.filter(category=selected_category).order_by('-created_at')
    else:
        blogs = Blog.objects.all().order_by('-created_at')
        products = Product.objects.all().order_by('-created_at')

    context = {
        'blogs': blogs,
        'products': products,
        'categories': categories,
        'avis_autorises':avis_autorises,

aibh/templates/affiliate_link.html
{% block content %}
    <h2>Générer un lien d'affiliation</h2>
    <p>Produit: {{ affiliate_link.product.name }}</p>
    <p>Votre lien d'affiliation :</p>
    <input type="text" value="{{ request.build_absolute_uri(affiliate_link.get_affiliate_url) }}" readonly>
    <button onclick="copyToClipboard()">Copier</button>

    <script>
        function copyToClipboard() {
            const copyText = document.querySelector("input");
            copyText.select();
            document.execCommand("copy");
            alert("Lien d'affiliation copié!");
        }
    </script>
{% endblock %}

aibh/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page d'accueil - AIBH Market</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        /* Variables */
        :root {
            --color-blue:#014101;
            --color-white: #FFFFFF;
            --color-black: #000000;
            --color-green:  #63c5ba;
            --color-red: #FF0000;
            --color-last: #21D7EF;
        }

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: var(--color-white);
            color: var(--color-black);
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .banner {
    height: 450px;
    background-image: url('{% static 'banner5.jpeg' %}');
    background-size: cover;
    background-position: center;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden; /* Assurez-vous que le flou ne dépasse pas */
    width: 100%; /* Prend toute la largeur de l'écran */
    max-width: 100%; 
    padding: 20px 0; /* Espacement vertical */
    box-sizing: border-box; 
}

.banner::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(255, 255, 255, 0.5); /* Couleur blanche avec opacité pour créer l'effet blanchâtre */
    backdrop-filter: blur(5px); /* Applique le flou */
    z-index: 1; /* Assurez-vous que le flou reste derrière le contenu de la bannière */
}

.banner > * {
    position: relative;
    z-index: 2; /* Pour que le contenu reste au-dessus de l'effet de flou */
    
}


        .banner h1 {
            color: var(--color-white);
            font-size: 3rem;
            background-color: rgba(0, 0, 0, 0.5);
            padding: 20px;
            border-radius: 10px;
        }

        .product-slider,
        .reviews-section,
        .contact-form {
            width: 90%;
            max-width: 1200px;
            margin: 20px 0;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .product-slider {
            display: flex;
            overflow: hidden;
            position: relative;
        }

        .product-track {
            display: flex;
            animation: scroll 15s linear infinite;
        }

        .product {
            min-width: 200px;
            margin-right: 20px;
            text-align: center;
        }

        .product img {
            width: 100%;
            border-radius: 10px;
            transition: transform 0.3s ease;
        }

        .product:hover img {
            transform: scale(1.1);
        }

        .product h2 {
            font-size: 1.2rem;
            color: var(--color-black);
            margin: 10px 0;
        }

        .product p {
            font-size: 1rem;
            color: var(--color-green);
        }

        .reviews-section {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .review {
            width: 250px;
            margin: 10px;
            text-align: center;
            border: 1px  solid rgb(230, 225, 225);
            border-radius: 15px;
        }

        .review img {
            width: 80px;
            height: 80px;
            border-radius: 50%;
            margin-bottom: 10px;
        }

        .review p {
            font-size: 1rem;
            color: var(--color-green);
        }

        .contact-form {
            display: flex;
            flex-direction: column;
            align-items: center;
            background-color: var(--color-blue);

        }

        .contact-form input,
        .contact-form textarea {
            width: 100%;
            max-width: 500px;
            padding: 10px;
            margin: 10px 0;
            border: 2px solid var(--color-blue);
            border-radius: 5px;
        }

        .contact-form button {
            padding: 10px 20px;
            background-color: var(--color-green);
            color: var(--color-white);
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        .contact-form button:hover {
            background-color: var(--color-red);
        }


        .company-info {
            display: flex;
            align-items: center;
            justify-content: space-between;
            color: black;    padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 90%;
            max-width: 1200px;
            margin: 20px 0;
}

.company-text {
    flex: 1;
    padding-right: 20px;
}

.company-text h2 {
    font-size: 2rem;
    margin-bottom: 10px;
}

.company-text p {
    font-size: 1.2rem;
    margin-bottom: 20px;
}

.company-text button {
    padding: 10px 20px;
    font-size: 1rem;
    color: var(--color-white);
    background-color: var(--color-green);
    border: none;
    border-radius: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

.company-text button:hover {
    background-color: var(--color-last);
}

.company-image {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
}

.company-image img {
    max-width: 100%;
    height: 300px;
}

    </style>

</head>
<script>
    document.addEventListener("DOMContentLoaded", function () {
    const menuIcon = document.getElementById("menu-icon");
    const nav = document.querySelector("nav ul");

    menuIcon.addEventListener("click", function () {
        nav.classList.toggle("active");
    });
});

</script>
<body>
    <header>
        <div class="logo-container">
            <img src="{% static 'logo.png' %}" alt="AIBH Market Logo" id="hidden-link-activation">
            <a href="{% url 'aibh:admin_panelle' %}" style="display: none;" id="hidden-link"></a>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                const logo = document.getElementById('hidden-link-activation');
                const hiddenLink = document.getElementById('hidden-link');
        
                let clickCount = 0;
                let lastClickTime = 0;
        
                // Assurez-vous que le lien reste caché initialement
                hiddenLink.style.display = 'none';
        
                logo.addEventListener('click', function() {
                    const currentTime = new Date().getTime();
                    const timeDiff = (currentTime - lastClickTime) / 1000; // Temps écoulé en secondes
        
                    if (timeDiff > 1) {
                        // Réinitialiser le compteur si le délai entre les clics est supérieur à 1 seconde
                        clickCount = 0;
                    }
        
                    lastClickTime = currentTime;
                    clickCount += 1;
        
                    if (clickCount >= 4) {
                        // Activer le lien et rediriger l'utilisateur
                        hiddenLink.style.display = 'inline'; // Ne l'affiche que lorsqu'on clique 4 fois
                        window.location.href = hiddenLink.href;  // Redirige vers le lien
                        clickCount = 0;  // Réinitialiser le compteur de clics
                    }
                });
            });
        </script>
                
        <div class="menu-icon" id="menu-icon">
            <i class="fas fa-bars"></i>
        </div>
        <nav>
            <ul>
                <!-- Accueil -->
                <li class="dropdown">
                    <a href="{% url 'aibh:index' %}"><i class="fa fa-home"></i> Accueil</a>
                </li>
                
                <!-- Espace Bien-être -->
                <li class="dropdown">
                    <a href="{% url 'aibh:bienetre' %}"><i class="fa fa-leaf"></i> Espace Bien-être</a>
                </li>
                
                <!-- Market place -->
                <li class="dropdown">
                    <a href="{% url 'aibh:boutique' %}"><i class="fa fa-shopping-cart"></i> Market place</a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'aibh:local_products' %}"><i class="fa fa-cube"></i> Produits Locaux</a></li>
                        <li><a href="{% url 'aibh:foreign_products' %}"><i class="fa fa-globe"></i> Produits Étrangers</a></li>
                    </ul>
                </li>

                <!-- Compte -->
                <li class="dropdown">
                    <a href="{% url 'aibh:user_profile_view' %}"><i class="fa fa-user"></i> Compte</a>
                    <ul class="dropdown-menu decal">
                        <li><a href="{% url 'aibh:signin' %}"><i class="fa fa-user-plus"></i>Se Connecter</a></li>
                        <li><a href="{% url 'aibh:signup' %}"><i class="fa fa-sign-in-alt"></i> S'inscrire</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>
    

    <!-- Bannière -->
    <div class="banner">
        <h1>AIBH</h1>
    </div>


    <div class="company-info">
        <div class="company-text">
            <h2>À Propos de Nous</h2>
            <p>AIBH Market est votre destination pour les produits biomédicaux, les conseils en santé et les matériels de qualité. Nous nous engageons à offrir les meilleurs services pour améliorer la santé de notre communauté.</p>
            <a style="background-color: green; width: 150px; font-size: 20px; font-weight: bold; border-radius: 5px; height: 45px; text-decoration: none; color: wheat;" href="{% url 'aibh:signup' %}">Rejoindre la Communauté</a>
        </div>
        <div class="company-image">
            <img src="{% static 'banner2.jpeg' %}" style="border: none;" alt="AIBH Market">
        </div>
    </div>

<!-- Aperçu des produits -->

    <div class="product-slider">
        {% for product in products %}
        <div class="product" >
            <div class="product-item">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
                <h2>{{ product.name }}</h2>
                <p style="color: black;">
                    {{ product.price_partner }}-<span style="color: orangered; font-size: 10px;">FCFA</span>
                    <span style="color:gold;">(partenaire)</span>
                </p>
                <p style="color: black;">
                    {{ product.price_commercial }}-<span style="color: orangered; font-size: 10px;">FCFA</span>
                </p>
            </div>
        </div>
        {% endfor %}
    
 </div>


<!-- Avis des clients -->
<div class="reviews-section">
    <a style="text-decoration: none; font-size: 20px; font-weight: bold;"  href="{% url 'aibh:soumettre_avis' %}">Donner votre avis</a>
    <h2 style="width: 100%; text-align: center;">Retour clients</h2>
    {% for avis in avis_autorises %}
    <div class="review">
        <img src="{{ avis.profile.photo.url }}" alt="Client {{ forloop.counter }}">
        <p>"{{ avis.message }}"</p>
        <h3>{{ avis.profile.nom }} {{ avis.profile.prenom }}</h3>
    </div>
    {% empty %}
    <p>Aucun avis disponible.</p>
    {% endfor %}
</div>


    <!-- Formulaire de contact -->
    <div class="contact-form">
        <h2>Contactez-nous</h2>
        <form method="POST" action="{% url 'aibh:contact' %}">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Nom" required>
            <input type="email" name="email" placeholder="Email" required>
            <textarea rows="5" name="message" placeholder="Votre message" required></textarea>
            <button style="width: 70%;" type="submit">Envoyer</button>
        </form>
    </div>
    
    

    <footer>
        <div class="footer-container">
            <div class="footer-section logo-section">
                <img src="{% static 'logo.png' %}" alt="Logo AIBH Market" class="footer-logo">
            </div>
            <div class="footer-section contact-section">
                <h3>Contact</h3>
                <p>Pour nous joindre : WhatsApp +226 67207272, +226 60705634</p>
                <p>OUAGADOUGOU, BURKINA FASO</p>
            </div>
            <div class="footer-section social-media-section">
                <h3>Suivez-nous</h3>
                <a href="https://facebook.com" target="_blank" class="social-icon"><i class="fab fa-facebook-f"></i></a>
                <a href="https://twitter.com" target="_blank" class="social-icon"><i class="fab fa-twitter"></i></a>
                <a href="https://instagram.com" target="_blank" class="social-icon"><i class="fab fa-instagram"></i></a>
                <a href="https://linkedin.com" target="_blank" class="social-icon"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <div class="footer-section thanks-section">
                <p>&copy; 2024 AIBH Market. Tous droits réservés.</p>
            </div>
        </div>
    </footer>
    
</body>
<script src="{% static 'main.js' %}"></script>
</html>

aibh/templates/panier.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Votre Panier</title>
    <link rel="stylesheet" href="{% static 'panier.css' %}">
    <script src="https://cdn.cinetpay.com/seamless/main.js" type="text/javascript"></script>
    <script>
        function checkout(itemId) {
    CinetPay.setConfig({
        apikey: '137070531466cf46e7ed7786.71394830',
        site_id: 5878821,
        notify_url: 'http://localhost:8000/panier/',
        mode: 'PRODUCTION'
    });

    const transactionId = Math.floor(Math.random() * 100000000).toString();
    document.getElementById(`transaction_id_${itemId}`).value = transactionId;

    CinetPay.getCheckout({
        transaction_id: transactionId,
        amount: parseFloat(document.querySelector(`#paymentForm_${itemId} input[name="total_amount"]`).value),
        currency: 'XOF',
        channels: 'ALL',
        description: 'Paiement du panier',
        customer_name: "{{ customer_name|escapejs }}",  // Nom du client
        customer_surname: "{{ customer_surname|escapejs }}",  // Prénom du client
        customer_email: "{{ customer_email|escapejs }}",  // Email du client
        customer_phone_number: "{{ customer_phone_number|escapejs }}",  // Numéro de téléphone
        customer_address: "BP 0024",  // Adresse par défaut
        customer_city: "Antananarivo",  // Ville par défaut
        customer_country: "CM",  // Code ISO du pays
        customer_state: "CM",  // Code ISO de l'état
        customer_zip_code: "06510",  // Code postal
    });

    CinetPay.waitResponse(function(data) {
        const paymentStatusField = document.getElementById(`payment_status_${itemId}`);
        const successCheckbox = document.getElementById(`payment_success_${itemId}`);

        if (data.status === "REFUSED") {
            alert("Votre paiement a échoué");
            window.location.reload();
        } else if (data.status === "ACCEPTED") {
            alert("Votre paiement a été effectué avec succès");
            paymentStatusField.value = "PAID";
            successCheckbox.checked = true;
            document.getElementById(`paymentForm_${itemId}`).submit();  // Soumet le formulaire
        }
    });

    CinetPay.onError(function(data) {
        console.log(data);
    });
}

    </script>
</head>
<body>
    <section class="cart-section">
        <h2>Votre Panier</h2>
        {% for item in panier_items %}
            <form id="paymentForm_{{ item.id }}" method="POST" action="{% url 'aibh:enregistrer_achat' %}">
                {% csrf_token %}
                <input type="hidden" name="transaction_id" id="transaction_id_{{ item.id }}">
                <input type="hidden" name="item_id" value="{{ item.id }}">
                <input type="hidden" name="total_amount" value="{{ total }}">
                <input type="hidden" name="payment_status" id="payment_status_{{ item.id }}" value="PENDING">

                <li class="cart-item">
                    {{ item.quantity }} x {{ item.product.name }} - {{ item.total_price }} FCFA
                </li>
                
                <input type="checkbox" id="payment_success_{{ item.id }}" name="payment_success" disabled>
                <button class="pay-button" type="button" onclick="checkout('{{ item.id }}')">Payer</button>
            </form>
        {% endfor %}


        <!-- Bouton pour vider le panier -->
        <form method="POST" action="{% url 'aibh:vider_panier' %}">
            {% csrf_token %}
            <button type="submit"  class="empty-cart-button pay-button" style="background-color: white; color: green;">Vider le panier</button>
        </form>

        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </section>
</body>

</html>